# Generated by Django 6.0.2 on 2026-03-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_specialistdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('autism', 'Autism'), ('speech_therapy', 'Speech Therapy'), ('adhd', 'ADHD'), ('sensory_processing', 'Sensory Processing'), ('social_development', 'Social Development'), ('physical_therapy', 'Physical Therapy'), ('behavioral_support', 'Behavioral Support'), ('learning_disabilities', 'Learning Disabilities')], max_length=255)),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Продолжительность курса в часах')),
                ('preview_image', models.ImageField(upload_to='courses/previews/')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('article', 'Статья'), ('pdf', 'PDF'), ('video', 'Видео')], max_length=20)),
                ('file', models.FileField(upload_to='courses/materials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
        ),
    ]
