# Generated by Django 6.0.3 on 2026-03-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursepurchase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursepurchase',
            name='unique_course_purchase_per_user',
        ),
    ]
