# Generated by Django 6.0.2 on 2026-02-18 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя ребёнка')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('development_type', models.CharField(blank=True, choices=[('autism', 'Аутизм (РАС)'), ('down_syndrome', 'Синдром Дауна'), ('zpr', 'ЗПР'), ('unknown', 'Пока не знаем / не уверены')], max_length=20, null=True)),
                ('communication_style', models.CharField(blank=True, choices=[('no_speech', 'Не говорит'), ('single_words', 'Говорит отдельные слова'), ('phrases', 'Говорит фразами'), ('fluent', 'Говорит свободно')], max_length=30, null=True)),
                ('understands_instructions', models.CharField(blank=True, choices=[('gestures_pictures', 'Только жесты / картинки'), ('short_instructions', 'Короткие инструкции'), ('understands_explanations', 'Понимает объяснения')], max_length=30, null=True)),
                ('sensory_sensitivities', models.JSONField(blank=True, default=list, help_text='Чувствительность к: громкие звуки, яркий свет, анимации и т.д.')),
                ('motor_difficulties', models.JSONField(blank=True, default=list, help_text='Сложности: маленькие кнопки, удержание пальца, drag&drop.')),
                ('behavior_notices', models.JSONField(blank=True, default=list, help_text='Что замечаете чаще: устаёт, расстраивается при ошибке и т.д.')),
                ('motivators', models.JSONField(blank=True, default=list, help_text='Что радует: звёзды, аплодисменты, наклейки, мультик после занятия.')),
                ('interests', models.JSONField(blank=True, default=list)),
                ('comfortable_duration', models.CharField(blank=True, choices=[('5_min', '5 минут'), ('10_min', '10 минут'), ('15_min', '15 минут'), ('flexible', 'Свободно')], max_length=20, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.userprofile')),
            ],
        ),
    ]
