# Generated by Django 6.0.2 on 2026-02-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стаж работы')),
                ('methods', models.JSONField(blank=True, default=list)),
                ('age_range', models.CharField(blank=True, max_length=255, verbose_name='Возраст детей')),
                ('development_types', models.JSONField(blank=True, default=list)),
                ('work_format', models.CharField(blank=True, choices=[('offline', 'Офлайн'), ('online', 'Онлайн')], max_length=20, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('time_zone', models.CharField(blank=True, max_length=63, verbose_name='Часовой пояс')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('provide_individual_consultations', models.BooleanField(default=False, verbose_name='Индивидуальные консультации')),
                ('work_with_child_through_parent', models.BooleanField(default=False, verbose_name='Работа с ребёнком через родителя')),
                ('provide_recommendations_and_plans', models.BooleanField(default=False, verbose_name='Рекомендации и планы занятий')),
                ('track_progress_and_analytics', models.BooleanField(default=False, verbose_name='Прогресс и аналитика')),
                ('specialist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='accounts.specialist')),
            ],
        ),
    ]
