# Generated by Django 6.0.3 on 2026-03-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_specialistdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/avatars/'),
        ),
    ]
