# Generated by Django 6.0.3 on 2026-04-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_specialist_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_info', to='accounts.userprofile')),
            ],
        ),
    ]
