# Generated by Django 6.0.3 on 2026-03-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0005_specialist_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_feeling', models.CharField(choices=[('good', 'Хорошо'), ('normal', 'Нормально'), ('hard', 'Сложно'), ('very_hard', 'Очень тяжело')], max_length=20, verbose_name='Общее самочувствие')),
                ('emotions', models.JSONField(blank=True, default=list, verbose_name='Эмоции за день')),
                ('observations', models.JSONField(blank=True, default=list, verbose_name='Наблюдения за день')),
                ('sleep_quality', models.CharField(choices=[('good', 'Хороший'), ('normal', 'Обычный'), ('bad', 'Плохой')], max_length=10, verbose_name='Сон')),
                ('appetite_quality', models.CharField(choices=[('good', 'Хороший'), ('normal', 'Обычный'), ('bad', 'Плохой')], max_length=10, verbose_name='Аппетит')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_trackings', to='accounts.child')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
